name: React App Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: install java
      uses: actions/setup-java@v3
      with: 
        java-version: 17
        distribution: adopt
        cache: gradle

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        sdk-platform: 'platforms;android-29'

    - name: Create local.properties file
      run: echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties  

    - name: Build Android app
      run: |
           npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
           cd android && chmod +x gradlew
           ./gradlew assembleDebug --warning-mode all
    - name: Upload application
      uses: actions/upload-artifact@v2
      with:
         name: app
         path: android/app/build/outputs/**/*.apk
         retention-days: 3      

